# use a node image as the base image and name it 'build' for
# later reference
FROM node:18.18-alpine3.18 as build

# set the working directory to /app
WORKDIR /app
# copy the current directory contents into the container at /app
COPY package.json /app/
RUN npm install
COPY . /app/
RUN npm run build --prod

# Use the latest version of the official Nginx image as the base image
FROM nginx:alpine
# copy the custom nginx configuration file to the container in the default
# location
RUN apk update && apk upgrade && \
    apk --update add logrotate openssl bash && \
    apk add --no-cache certbot certbot-nginx

RUN adduser -D -H -u 1000 -s /bin/bash www-data -G www-data
RUN apk del --no-cache

COPY .nginx/nginx.conf /etc/nginx/nginx.conf
# copy the built application from the build stage to the nginx html
# directory
COPY --from=build /app/dist/base-app /usr/share/nginx/html
COPY .nginx/.htaccess  /usr/share/nginx/html


CMD ["nginx", "-g", "daemon off;"]
# The above commands build the Angular app and then configure and build a
# Docker image for serving it using the nginx web server.
