export interface EmpresaRequest {
  idCliente?: string,
  idFornecedor?: string,
  nome: string,
  cnpj: string,
  fantasia: string,
  responsavel: string,
  inscricaoEstadual: string,
  contato1: string,
  contato2: string,
  email: string,
  isCliente?: boolean,
  isFornecedor?: boolean,
  cep: string,
  logradouro: string,
  bairro: string,
  numero: string,
  cidade: string,
  estado: string,
  complemento: string
}
